mod state;
mod commands;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(state::Store::new_with_runtime())
        .invoke_handler(tauri::generate_handler![
            commands::ping,
            commands::get_state,
            commands::select_session,
            commands::create_session,
            commands::archive_session,
            commands::rename_session,
            commands::submit_composer,
            commands::cancel_current_run,
            commands::set_active_view,
            commands::set_sidebar_collapsed,
            commands::get_default_model,
            commands::get_models,
            commands::get_providers,
            commands::get_model_settings,
            commands::set_default_model,
            commands::set_default_thinking_level,
            commands::set_provider_api_key,
            commands::login_provider,
            commands::logout_provider,
            commands::set_custom_provider,
            commands::delete_custom_provider,
            commands::set_model_settings_scope_mode,
            commands::list_skills,
            commands::get_skill,
            commands::delete_skill,
            commands::list_extensions,
            commands::get_extension,
            commands::delete_extension,
            commands::set_theme_mode,
            commands::set_theme_preset_id,
            commands::get_theme_mode,
            commands::get_resolved_theme,
            commands::set_notification_preferences,
            commands::set_integrated_terminal_shell,
            commands::set_enable_transparency,
            commands::get_notification_permission_status,
            commands::request_notification_permission,
            commands::open_system_notification_settings,
            commands::get_selected_transcript,
            commands::toggle_window_maximize,
            commands::open_external,
            commands::list_custom_providers,
            commands::get_custom_provider,
            commands::probe_custom_provider_models,
            commands::has_provider_auth,
            commands::update_composer_draft,
            commands::add_composer_attachments,
            commands::remove_composer_attachment,
            commands::edit_queued_composer_message,
            commands::cancel_queued_composer_edit,
            commands::remove_queued_composer_message,
            commands::steer_queued_composer_message,
            commands::pick_composer_attachments,
        ])
        .run(tauri::generate_context!())
        .expect("error while running pi-gui-rs");
}
